# Generated by Django 3.2.2 on 2021-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_auto_20210420_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='starus',
            new_name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(to='user_accounts.Tag'),
        ),
    ]
