# Generated by Django 3.2.2 on 2021-05-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='producto',
            new_name='product',
        ),
    ]
